In [2]:
import torch
import torch.nn as nn
import pandas as pd

In [43]:
split = df[0].str.split(" ", n = 1, expand = True)
df["word"] = split[0]
df['embedding'] = split[1]
df = df.drop(0, axis = 1)

In [135]:
adj_mat = pd.read_csv("./LatentSemanticImputation/word_classification/matrices/affMat.csv", index_col=0).drop('y', axis = 1)
y = pd.read_csv("./LatentSemanticImputation/word_classification/matrices/affMat.csv", index_col=0)['y']
adj_mat_index = adj_mat.index.to_list()

In [57]:
glove_mat = pd.read_csv("./LatentSemanticImputation/word_classification/matrices/gloveMat.csv", index_col=0)
glove_mat_index = glove_mat.index.to_list()

In [137]:
train_mask = []
for i in range(len(adj_mat)):
    
    if adj_mat_index[i] in glove_mat_index:
        train_mask.append(i)

In [138]:
adj_mat.iloc[train_mask, :]

REGN US EQUITY  UNM US EQUITY  UAL US EQUITY  OKE US EQUITY  \
Facebook           0.174052       0.059304       0.119060       0.230242   
Varian             0.184139       0.137700       0.139299       0.207374   
Allergan           0.381017       0.210642       0.124967       0.187746   
Nucor              0.298215       0.398885       0.240242       0.336522   
Ventas             0.049587      -0.084660       0.025188       0.151018   
...                     ...            ...            ...            ...   
Caterpillar        0.205736       0.435696       0.257313       0.397402   
Paychex            0.170059       0.273242       0.257718       0.178883   
Verizon            0.137301       0.219420       0.094678       0.229011   
CBS                0.136909       0.177134       0.162548       0.235502   
Micron             0.220560       0.165679       0.213872       0.162912   

             FB US EQUITY  KMI US EQUITY  SEE US EQUITY  TSN US EQUITY  \
Facebook         1.000000       0.247885       0.172003       0.040786   
Varian           0.224253       0.193266       0.209721       0.134276   
Allergan         0.231772       0.270169       0.170589       0.107218   
Nucor            0.217959       0.354948       0.240763       0.112764   
Ventas           0.134698       0.127352       0.136452       0.190339   
...                   ...            ...            ...            ...   
Caterpillar      0.256198       0.414976       0.279788       0.152498   
Paychex          0.270607       0.193413       0.262494       0.193482   
Verizon          0.099680       0.201607       0.228568       0.222397   
CBS              0.089609       0.214689       0.168751       0.188760   
Micron           0.319637       0.156404       0.163711       0.135854   

             ADI US EQUITY  VAR US EQUITY  ...  ESRX US EQUITY  KMB US EQUITY  \
Facebook          0.317664       0.224253  ...        0.078280       0.043405   
Varian            0.266714       1.000000  ...        0.189190       0.190341   
Allergan          0.137791       0.194863  ...        0.337122       0.118802   
Nucor             0.345370       0.194020  ...        0.222170       0.079512   
Ventas            0.109947       0.173121  ...       -0.002850       0.293259   
...                    ...            ...  ...             ...            ...   
Caterpillar       0.381698       0.294469  ...        0.146817       0.175994   
Paychex           0.296862       0.274664  ...        0.206971       0.255320   
Verizon           0.145348       0.174770  ...        0.195862       0.330930   
CBS               0.234295       0.153285  ...        0.152543       0.220684   
Micron            0.494168       0.183849  ...        0.051211       0.137565   

             CAT US EQUITY  COO US EQUITY  PAYX US EQUITY  VZ US EQUITY  \
Facebook          0.256198       0.283525        0.270607      0.099680   
Varian            0.294469       0.391466        0.274664      0.174770   
Allergan          0.218019       0.275083        0.203009      0.203908   
Nucor             0.472798       0.140169        0.310611      0.220304   
Ventas           -0.003764       0.154518        0.214044      0.269318   
...                    ...            ...             ...           ...   
Caterpillar       1.000000       0.192889        0.330391      0.177649   
Paychex           0.330391       0.275410        1.000000      0.334160   
Verizon           0.177649       0.162602        0.334160      1.000000   
CBS               0.201727       0.088809        0.218312      0.228174   
Micron            0.260264       0.152877        0.264228      0.124103   

             UNP US EQUITY  XL US EQUITY  CBS US EQUITY  MU US EQUITY  
Facebook          0.155670      0.038570       0.089609      0.319637  
Varian            0.132389      0.094268       0.153285      0.183849  
Allergan          0.227528      0.159227       0.148689      0.133125  
Nucor             0.411078      0.083219       0.

In [179]:
glove_mat.drop(['300','301'], axis = 1)

0        1         2        3         4         5  \
Facebook    -0.040208  0.45172 -0.293000  0.43092 -0.009503 -0.110830   
Varian       0.293450  0.22605  0.145180  0.58848  0.075919 -0.700200   
Allergan     0.683800  0.29279  0.065342  0.28826 -0.101740 -0.245000   
Nucor        0.317200  0.24979  0.644430 -0.86224 -0.658380 -0.149300   
Ventas       0.028289 -0.25496 -0.040969 -0.10904  0.792440  0.059963   
...               ...      ...       ...      ...       ...       ...   
Caterpillar  0.351770  0.68704  0.060574 -0.55106  0.377650  0.726630   
Paychex     -0.336440 -0.14342  0.113880 -0.40520 -0.370650  0.547330   
Verizon      0.184220  0.80397 -0.022202 -0.46364  0.523490 -0.000045   
CBS         -0.078176  0.61518  0.013317 -0.20788 -0.215350 -0.072729   
Micron       0.012676  0.91376 -0.132040  0.52081 -0.136130  0.082593   

                    6         7         8         9  ...       290       291  \
Facebook     0.406940 -0.506720  0.296620  1.071500  ... -0.345840  0.176720   
Varian      -0.004007 -0.511050  0.550760 -1.586700  ... -0.084799 -0.257310   
Allergan    -0.144320 -0.019873  0.286190 -1.409600  ...  0.140720  1.153000   
Nucor       -0.481660  0.583130 -0.664520 -1.502900  ...  0.598320  0.377250   
Ventas       0.469690  0.023215 -0.115990 -1.375500  ...  0.406520  0.297500   
...               ...       ...       ...       ...  ...       ...       ...   
Caterpillar -0.498810  0.038883  0.343790 -0.246330  ... -0.378060  0.403360   
Paychex     -0.704830  0.285130  0.103730 -1.203400  ... -0.099349 -0.009112   
Verizon      0.592550 -0.566330  0.217670  0.133100  ... -0.582070  0.119990   
CBS         -0.047071  0.381820  0.447700  0.061162  ...  0.365100 -0.365360   
Micron      -0.226780  0.088426 -0.073635 -1.658200  ...  0.071193 -0.044730   

                  292       293      294       295       296      297  \
Facebook     0.599150  0.202340  0.61720 -0.052586  0.094889 -0.34720   
Varian       0.399100 -0.294570  0.75516  0.038374 -0.209770  0.66269   
Allergan     0.029328 -0.535550 -0.66531 -0.742790 -0.578870 -0.16450   
Nucor        0.282570 -0.096784  0.23995  0.029166 -0.217890  0.34788   
Ventas       0.263000  0.083026  0.11912  0.334980  0.184730 -0.25284   
...               ...       ...      ...       ...       ...      ...   
Caterpillar  0.429540  0.128600 -0.41179  0.174050  0.375210  1.16670   
Paychex     -0.191240  0.693950  0.73308 -0.150940 -0.082760  0.51411   
Verizon      0.067291  0.319180  0.10673  0.238320 -0.189690  0.67368   
CBS         -0.626860  0.327580  0.39976 -0.666960 -0.443200 -0.49635   
Micron       0.350150 -0.026506 -0.56719  0.357310 -0.293130  0.37989   

                  298       299  
Facebook    -0.481800  0.685650  
Varian      -0.480290  0.316030  
Allergan    -0.039523  0.085159  
Nucor       -1.183100 -0.383080  
Ventas      -0.382130  0.069614  
...               ...       ...  
Caterpillar -0.170780 -0.186700  
Paychex     -0.018055  0.352740  
Verizon     -0.667880  1.019000  
CBS         -0.145220 -0.153410  
Micron      -0.393340  0.393210  

[206 rows x 300 columns]

In [61]:
glove_mat.shape

(206, 302)

In [65]:
np.sum(glove_mat.to_numpy(), 1)

array([8.62839528e+03, 3.35520971e+02, 3.70228589e+02, 9.61337608e+01,
       5.21437687e+01, 1.09679194e+04, 8.08318856e+01, 2.64422898e+02,
       1.83737476e+02, 1.71661393e+02, 2.07609446e+02, 5.22876925e+02,
       3.55796577e+02, 3.38508134e+02, 2.04497356e+02, 3.86013535e+02,
       7.51599113e+01, 8.81214679e+02, 9.79379356e+01, 1.10027770e+02,
       1.47757913e+02, 5.91000218e+02, 3.12953561e+02, 3.05999989e+02,
       1.27699493e+04, 2.13363441e+02, 3.53982132e+02, 1.40049899e+02,
       4.85952781e+02, 1.98454685e+03, 7.97090320e+02, 1.83644460e+03,
       6.05370708e+02, 3.63341304e+02, 1.01779467e+03, 2.44490361e+02,
       1.52021637e+03, 2.17256448e+02, 6.53265172e+02, 1.37387690e+03,
       1.46274678e+03, 1.39054093e+03, 1.80046220e+03, 1.65188836e+02,
       2.48547616e+03, 1.40507446e+02, 5.80925638e+02, 4.17794085e+02,
       5.61771925e+01, 1.31160755e+02, 1.26471131e+02, 1.56333340e+02,
       2.30877491e+03, 1.35816707e+04, 1.15615920e+02, 2.72752018e+03,
      

In [183]:
adj_mat = pd.read_csv("./LatentSemanticImputation/word_classification/matrices/affMat.csv", index_col=0)
adj_mat

REGN US EQUITY  UNM US EQUITY  UAL US EQUITY  \
Regeneron                 1.000000       0.151142       0.105208   
Unum_Group                0.151142       1.000000       0.283075   
United_Continental        0.105208       0.283075       1.000000   
ONEOK                     0.069935       0.149528       0.143929   
Facebook                  0.174052       0.059304       0.119060   
...                            ...            ...            ...   
Verizon                   0.137301       0.219420       0.094678   
Union_Pacific             0.157936       0.421148       0.291897   
XL_Capital                0.084560       0.177677       0.094481   
CBS                       0.136909       0.177134       0.162548   
Micron                    0.220560       0.165679       0.213872   

                    OKE US EQUITY  FB US EQUITY  KMI US EQUITY  SEE US EQUITY  \
Regeneron                0.069935      0.174052       0.230379       0.120237   
Unum_Group               0.149528      0.059304       0.251403       0.279716   
United_Continental       0.143929      0.119060       0.189908       0.189188   
ONEOK                    1.000000      0.230242       0.642033       0.179999   
Facebook                 0.230242      1.000000       0.247885       0.172003   
...                           ...           ...            ...            ...   
Verizon                  0.229011      0.099680       0.201607       0.228568   
Union_Pacific            0.251607      0.155670       0.283853       0.252752   
XL_Capital               0.041569      0.038570       0.081097       0.139263   
CBS                      0.235502      0.089609       0.214689       0.168751   
Micron                   0.162912      0.319637       0.156404       0.163711   

                    TSN US EQUITY  ADI US EQUITY  VAR US EQUITY  ...  \
Regeneron                0.092692       0.203464       0.184139  ...   
Unum_Group               0.142772       0.287477       0.137700  ...   
United_Continental       0.073910       0.255691       0.139299  ...   
ONEOK                    0.116641       0.193932       0.207374  ...   
Facebook                 0.040786       0.317664       0.224253  ...   
...                           ...            ...            ...  ...   
Verizon                  0.222397       0.145348       0.174770  ...   
Union_Pacific            0.140541       0.303513       0.132389  ...   
XL_Capital               0.030380       0.051647       0.094268  ...   
CBS                      0.188760       0.234295       0.153285  ...   
Micron                   0.135854       0.494168       0.183849  ...   

                    KMB US EQUITY  CAT US EQUITY  COO US EQUITY  \
Regeneron                0.116291       0.205736       0.210796   
Unum_Group               0.082835       0.435696       0.138003   
United_Continental       0.017188       0.257313       0.121235   
ONEOK                    0.106359       0.397402       0.098413   
Facebook                 0.043405       0.256198       0.283525   
...                           ...            ...            ...   
Verizon                  0.330930       0.177649       0.162602   
Union_Pacific            0.140498       0.519631       0.175340   
XL_Capital               0.022977       0.132128       0.097885   
CBS                      0.220684       0.201727       0.088809   
Micron                   0.137565       0.260264       0.152877   

                    PAYX US EQUITY  VZ US EQUITY  UNP US EQUITY  XL US EQUITY  \
Regeneron                 0.170059      0.137301       0.157936      0.084560   
Unum_Group                0.273242      0.219420       0.421148      0.177677   
United_Continental        0.257718      0.094678       0.291897      0.094481   
ONEOK                     0.178883      0.229011       0.251607      0.041569   
Facebook                  0.270607      0.099680       0.155670      0.038570   
...                            ...           ...            ...           

In [193]:
pd.read_csv("./LatentSemanticImputation/word_classification/matrices/fullMat.csv", index_col=0)

0         1         2         3         4  \
Regeneron           0.841414  1.512317  0.675493  2.357999  0.529899   
Unum_Group         -0.208115 -0.077768  1.278303  0.020541 -0.477928   
United_Continental  0.084431  0.236514  0.554012 -0.389547 -0.649251   
ONEOK              -1.027363 -0.455291  1.718671  0.162770  0.018373   
Facebook            0.038943  0.157847  0.177917 -0.115327 -0.410939   
...                      ...       ...       ...       ...       ...   
Verizon            -0.398314 -0.230092  0.620022 -0.094381 -0.440382   
Union_Pacific       0.150045 -0.230192  0.813774 -0.054360  0.136712   
XL_Capital         -0.631991  0.116216 -0.098082 -0.146328 -1.157523   
CBS                -0.032082  0.009271  0.140478 -0.042760 -0.292019   
Micron             -0.702741 -0.785512 -0.144391 -0.056021 -2.280065   

                           5         6         7         8         9  ...  \
Regeneron           1.164875  0.515220  0.644450 -1.810016  1.458016  ...   
Unum_Group          1.466457  1.397962  0.291432 -1.627205  0.698964  ...   
United_Continental  1.950099  0.366168 -0.267554  1.249782 -0.661467  ...   
ONEOK               0.936929 -0.253952  0.980365 -0.363804  0.068560  ...   
Facebook            0.250816 -0.007706  0.245558 -0.261293 -0.001941  ...   
...                      ...       ...       ...       ...       ...  ...   
Verizon            -0.840239  0.351482 -0.453634 -0.388228  0.302094  ...   
Union_Pacific      -0.503516 -0.966860 -0.327242  0.731094  0.069843  ...   
XL_Capital         -0.469466 -0.278321  0.189413 -0.594333 -1.217302  ...   
CBS                 0.274143  0.036753  0.322229 -0.048576 -0.019123  ...   
Micron              0.316088 -1.327741  1.735412 -1.682847 -0.601753  ...   

                         192       193       194       195       196  \
Regeneron           1.786929  0.325655  0.770299 -0.452478 -1.058615   
Unum_Group          0.157945  0.342220  2.248742  2.426607  1.039774   
United_Continental  0.046424 -2.268419  0.949810 -0.813032  0.499300   
ONEOK              -0.415700 -0.322723  0.293735 -1.695609  0.249339   
Facebook           -0.142390 -0.033943  0.151629 -0.068005  0.187972   
...                      ...       ...       ...       ...       ...   
Verizon            -0.603971 -0.139281  0.207346  0.357481 -0.322063   
Union_Pacific       0.147799 -0.191914  0.183549  0.382704 -0.894925   
XL_Capital          0.531234 -1.204304  1.339710  0.648093  1.000391   
CBS                -0.102400 -0.002767  0.109035 -0.079797 -0.096514   
Micron              0.846683  1.258807  0.315894  1.424337 -0.213261   

                         197       198       199  200   201  
Regeneron          -0.191484  0.923177 -0.342697    6    76  
Unum_Group         -1.430837  0.819338 -2.096831    1     4  
United_Continental  0.340172 -0.562814  0.286384    4    71  
ONEOK               0.143881 -2.337736 -0.454947    3    73  
Facebook           -0.116353 -0.445524 -0.183300   11  8621  
...                      ...       ...       ...  ...   ...  
Verizon            -0.407819 -0.622522 -0.544109    2  3255  
Union_Pacific      -0.427640 -1.112158 -0.492906    4  2054  
XL_Capital         -1.779307  0.027047  0.423247    1     6  
CBS                -0.089003 -0.185086 -0.104750   10  8521  
Micron             -0.781580 -0.615827 -0.951979   11   315  

[487 rows x 202 columns]

In [3]:
adj_mat = pd.read_csv("./LatentSemanticImputation/word_classification/matrices/affMat.csv", index_col=0).drop('y', axis = 1)

In [5]:
adj_mat

REGN US EQUITY  UNM US EQUITY  UAL US EQUITY  \
Regeneron                 1.000000       0.151142       0.105208   
Unum_Group                0.151142       1.000000       0.283075   
United_Continental        0.105208       0.283075       1.000000   
ONEOK                     0.069935       0.149528       0.143929   
Facebook                  0.174052       0.059304       0.119060   
...                            ...            ...            ...   
Verizon                   0.137301       0.219420       0.094678   
Union_Pacific             0.157936       0.421148       0.291897   
XL_Capital                0.084560       0.177677       0.094481   
CBS                       0.136909       0.177134       0.162548   
Micron                    0.220560       0.165679       0.213872   

                    OKE US EQUITY  FB US EQUITY  KMI US EQUITY  SEE US EQUITY  \
Regeneron                0.069935      0.174052       0.230379       0.120237   
Unum_Group               0.149528      0.059304       0.251403       0.279716   
United_Continental       0.143929      0.119060       0.189908       0.189188   
ONEOK                    1.000000      0.230242       0.642033       0.179999   
Facebook                 0.230242      1.000000       0.247885       0.172003   
...                           ...           ...            ...            ...   
Verizon                  0.229011      0.099680       0.201607       0.228568   
Union_Pacific            0.251607      0.155670       0.283853       0.252752   
XL_Capital               0.041569      0.038570       0.081097       0.139263   
CBS                      0.235502      0.089609       0.214689       0.168751   
Micron                   0.162912      0.319637       0.156404       0.163711   

                    TSN US EQUITY  ADI US EQUITY  VAR US EQUITY  ...  \
Regeneron                0.092692       0.203464       0.184139  ...   
Unum_Group               0.142772       0.287477       0.137700  ...   
United_Continental       0.073910       0.255691       0.139299  ...   
ONEOK                    0.116641       0.193932       0.207374  ...   
Facebook                 0.040786       0.317664       0.224253  ...   
...                           ...            ...            ...  ...   
Verizon                  0.222397       0.145348       0.174770  ...   
Union_Pacific            0.140541       0.303513       0.132389  ...   
XL_Capital               0.030380       0.051647       0.094268  ...   
CBS                      0.188760       0.234295       0.153285  ...   
Micron                   0.135854       0.494168       0.183849  ...   

                    ESRX US EQUITY  KMB US EQUITY  CAT US EQUITY  \
Regeneron                 0.252731       0.116291       0.205736   
Unum_Group                0.201408       0.082835       0.435696   
United_Continental        0.177650       0.017188       0.257313   
ONEOK                     0.101924       0.106359       0.397402   
Facebook                  0.078280       0.043405       0.256198   
...                            ...            ...            ...   
Verizon                   0.195862       0.330930       0.177649   
Union_Pacific             0.238561       0.140498       0.519631   
XL_Capital                0.030849       0.022977       0.132128   
CBS                       0.152543       0.220684       0.201727   
Micron                    0.051211       0.137565       0.260264   

                    COO US EQUITY  PAYX US EQUITY  VZ US EQUITY  \
Regeneron                0.210796        0.170059      0.137301   
Unum_Group               0.138003        0.273242      0.219420   
United_Continental       0.121235        0.257718      0.094678   
ONEOK                    0.098413        0.178883      0.229011   
Facebook                 0.283525        0.270607      0.099680   
...                           ...             ...           ...   
Verizon                  0.162602        0.334160      1.000000   
Union_Pacifi

In [26]:
def normalize_adj(adj):

    rowsum = np.sum(adj, 1)
    D_inv_sqrt = np.power(rowsum, -0.5).flatten()
    D_inv_sqrt[np.isinf(D_inv_sqrt)] = 0.
    D_mat_inv_sqrt = np.diag(D_inv_sqrt)
    return D_mat_inv_sqrt.dot(adj).dot(D_mat_inv_sqrt)

In [33]:
adj = np.array([[1,0.5,0.2],[0.3, 1, 0.5],[0.5,0.4, 1]])

In [34]:
normalize_adj(adj)

array([[0.58823529, 0.28583098, 0.11128298],
       [0.17149859, 0.55555556, 0.27036904],
       [0.27820744, 0.21629523, 0.52631579]])

In [35]:
adj

array([[1. , 0.5, 0.2],
       [0.3, 1. , 0.5],
       [0.5, 0.4, 1. ]])

In [36]:
(np.sqrt(1.7)*np.sqrt(1.8))

0.5716619504750294

In [40]:
rowsum = np.sum(adj, 1)
print(rowsum)
D_inv_sqrt = np.power(rowsum, -0.5).flatten()
print(D_inv_sqrt)
D_inv_sqrt[np.isinf(D_inv_sqrt)] = 0.
print(D_inv_sqrt)
D_mat_inv_sqrt = np.diag(D_inv_sqrt)
print(D_mat_inv_sqrt)
D_mat_inv_sqrt.dot(adj).dot(D_mat_inv_sqrt)

[1.7 1.8 1.9]
[0.76696499 0.74535599 0.72547625]
[0.76696499 0.74535599 0.72547625]
[[0.76696499 0.         0.        ]
 [0.         0.74535599 0.        ]
 [0.         0.         0.72547625]]


array([[0.58823529, 0.28583098, 0.11128298],
       [0.17149859, 0.55555556, 0.27036904],
       [0.27820744, 0.21629523, 0.52631579]])

In [45]:
D_mat_inv_sqrt.dot(adj).dot(D_mat_inv_sqrt)

array([[0.58823529, 0.28583098, 0.11128298],
       [0.17149859, 0.55555556, 0.27036904],
       [0.27820744, 0.21629523, 0.52631579]])

In [55]:
(1)/(np.sqrt(1.7)*np.sqrt(1.7))

0.5882352941176471

In [47]:
1/(np.sqrt(1.8)*np.sqrt(1.7))

0.5716619504750294

In [51]:
adj

array([[1. , 0.5, 0.2],
       [0.3, 1. , 0.5],
       [0.5, 0.4, 1. ]])